# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19e8BHXBQCD1pU4Me4wGJRiJFHlrGL5vW
"""

!pip install streamlit geopy
import streamlit as st
from geopy.distance import geodesic
import datetime

st.title("Smart Client Visit Optimizer")

# Start Location
st.header("Start Location")
start_lat = st.number_input("Start Latitude", value=9.9200)
start_lon = st.number_input("Start Longitude", value=78.1200)

# Clients
st.header("Client Details")
num_clients = st.number_input("Number of Clients", min_value=1, step=1)

clients = []

for i in range(int(num_clients)):
    st.subheader(f"Client {i+1}")
    name = st.text_input(f"Name {i}", key=f"name{i}")
    lat = st.number_input(f"Latitude {i}", key=f"lat{i}")
    lon = st.number_input(f"Longitude {i}", key=f"lon{i}")
    available_from = st.number_input(f"Available From (24h)", key=f"from{i}")
    available_to = st.number_input(f"Available To (24h)", key=f"to{i}")

    clients.append({
        "name": name,
        "lat": lat,
        "lon": lon,
        "from": available_from,
        "to": available_to
    })

if st.button("Generate Suggestion"):

    start = (start_lat, start_lon)
    current_time = 9   # Start at 9 AM
    speed = 35         # km/h average speed

    # Traffic logic (free simulation)
    hour = datetime.datetime.now().hour
    if 8 <= hour <= 10 or 17 <= hour <= 19:
        traffic_multiplier = 1.3
    else:
        traffic_multiplier = 1.0

    # Sort nearest first
    clients.sort(key=lambda c: geodesic(start, (c["lat"], c["lon"])).km)

    schedule = []

    for client in clients:
        distance_km = geodesic(start, (client["lat"], client["lon"])).km
        travel_minutes = (distance_km / speed) * 60 * traffic_multiplier
        arrival_time = current_time + travel_minutes / 60

        # Respect availability
        if arrival_time < client["from"]:
            arrival_time = client["from"]

        if arrival_time <= client["to"]:
            schedule.append((client["name"], round(arrival_time,2)))
            current_time = arrival_time + 1   # Assume 1 hour visit
            start = (client["lat"], client["lon"])

    st.success("Suggested Visit Plan")
    for item in schedule:
        st.write(f"{item[0]} at {item[1]} hrs")